/// Flutter icons InstaIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InstaIcons
///      fonts:
///       - asset: fonts/InstaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InstaIcons {
  InstaIcons._();

  static const _kFontFam = 'InstaIcons';

  static const IconData add_square = const IconData(0xe800, fontFamily: _kFontFam);
 
  static const IconData chat = const IconData(0xe802, fontFamily: _kFontFam);
  
  static const IconData heart = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData person = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData add_circle = const IconData(0xe80c, fontFamily: _kFontFam);
}
